services:
  # A Docker web service
  - type: web
    name: fastapi-crud-authentication
    runtime: python
    plan: free
    autoDeploy: false
    buildCommand: pip install -r requirements.txt
    startCommand: python main_basic_auth.py
